name: C/C++ Multiplatform Build

on:
  push:
    branches: [ "MAIN" ]
  pull_request:
    branches: [ "MAIN" ]

jobs:
  # 🐧 Linux build
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 and SDL2_ttf
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

      - name: Compile RPG Engine with Make
        working-directory: RPGMotor/
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpg-linux
          path: RPGMotor/build/rpg

  # 🪟 Windows build
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf

      - name: Compile RPG Engine with Make
        shell: msys2 {0}
        working-directory: RPGMotor/
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpg-windows
          path: RPGMotor/build/rpg.exe
